FROM node:15

WORKDIR /usr/src/app
#Copia tudo
COPY package*.json .
COPY src ./src/
RUN mkdir teste

RUN apt-get update && apt-get install -y wget

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN npm install

# Volume para poder alterar em tempo de dev
#VOLUME ./src:/usr/src/app/src

# Expõe a porta para que outros containers possa acessar.
EXPOSE 3000
#ENTRYPOINT [ "dockerize", "-wait", "tcp://db:3306", "-timeout", "300s", "docker-entrypoint.sh" ]# usa o dockerize para aguardar o mysql subir e depois chama o entrypoint da imagem (base) node
#CMD ["node", "src/index.js"]